<?php
namespace Vetra\Theme\Admin;
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class Dashboard {
	public function __construct() { add_action( 'admin_menu', array( $this, 'menu' ), 12 ); add_action( 'admin_post_vetra_admin_action', array( $this, 'handle' ) ); add_action( 'admin_enqueue_scripts', array( $this, 'assets' ) ); }
	public function menu() { add_theme_page( __( 'داشبورد وترا', 'vetra-portal-theme' ), __( 'داشبورد وترا', 'vetra-portal-theme' ), 'manage_options', 'vetra-dashboard', array( $this, 'render' ) ); }
	public function assets( $hook ) { if ( 'appearance_page_vetra-dashboard' !== $hook ) { return; } wp_enqueue_style( 'vetra-admin', VETRA_PORTAL_URI . '/assets/css/vetra-admin.css', array(), VETRA_PORTAL_VERSION ); wp_enqueue_script( 'vetra-admin-dashboard', VETRA_PORTAL_URI . '/assets/js/vetra-admin.js', array(), VETRA_PORTAL_VERSION, true ); }
	private function icon( $name ) { return function_exists( 'vetra_icon' ) ? vetra_icon( $name, array( 'size' => 20, 'decorative' => true ) ) : ''; }
	private function card( $id, $icon, $title, $content ) { echo '<section class="vetra-admin-panel" id="vetra-panel-' . esc_attr( $id ) . '" role="tabpanel" aria-labelledby="vetra-tab-' . esc_attr( $id ) . '"><div class="vetra-admin-card__header"><span class="vetra-admin-card__icon">' . $this->icon( $icon ) . '</span><div><h2>' . esc_html( $title ) . '</h2><p class="vetra-admin-card__hint">' . esc_html__( 'تنظیمات این بخش را با کنترل‌های واضح مدیریت کنید.', 'vetra-portal-theme' ) . '</p></div></div>' . $content . '</section>'; }
	public function render() {
		if ( ! current_user_can( 'manage_options' ) ) { wp_die( esc_html__( 'دسترسی کافی ندارید.', 'vetra-portal-theme' ) ); }
		$modules = array( 'Customizer' => true, 'PWA' => (bool) vetra_option( 'pwa_enabled' ), 'Elementor' => vetra_integration_is_active( 'elementor' ), 'Gravity Forms' => vetra_integration_is_active( 'gravityforms' ) );
		?><div class="wrap vetra-admin-dashboard" dir="<?php echo esc_attr( is_rtl() ? 'rtl' : 'ltr' ); ?>"><header class="vetra-admin-hero"><div><span class="vetra-admin-eyebrow">VETRA PORTAL / 3.9.0</span><h1><?php esc_html_e( 'مرکز کنترل وترا', 'vetra-portal-theme' ); ?></h1><p><?php esc_html_e( 'تنظیمات، وضعیت سرویس‌ها و ابزارهای نگهداری را در یک فضای منسجم مدیریت کنید.', 'vetra-portal-theme' ); ?></p></div><span class="vetra-admin-hero__mark"><?php echo $this->icon( 'dashboard-grid' ); ?></span></header><div class="vetra-admin-tabs" data-vetra-tabs><div class="vetra-admin-tablist" role="tablist" aria-label="<?php esc_attr_e( 'بخش‌های داشبورد', 'vetra-portal-theme' ); ?>"><button type="button" class="vetra-admin-tab is-active" role="tab" id="vetra-tab-overview" aria-controls="vetra-panel-overview" aria-selected="true" data-vetra-tab="overview"><?php echo $this->icon( 'dashboard-grid' ); ?><span><?php esc_html_e( 'خلاصه', 'vetra-portal-theme' ); ?></span></button><button type="button" class="vetra-admin-tab" role="tab" id="vetra-tab-design" aria-controls="vetra-panel-design" aria-selected="false" tabindex="-1" data-vetra-tab="design"><?php echo $this->icon( 'settings' ); ?><span><?php esc_html_e( 'طراحی', 'vetra-portal-theme' ); ?></span></button><button type="button" class="vetra-admin-tab" role="tab" id="vetra-tab-projects" aria-controls="vetra-panel-projects" aria-selected="false" tabindex="-1" data-vetra-tab="projects"><?php echo $this->icon( 'folder-project' ); ?><span><?php esc_html_e( 'پروژه‌ها', 'vetra-portal-theme' ); ?></span></button><button type="button" class="vetra-admin-tab" role="tab" id="vetra-tab-system" aria-controls="vetra-panel-system" aria-selected="false" tabindex="-1" data-vetra-tab="system"><?php echo $this->icon( 'settings' ); ?><span><?php esc_html_e( 'سیستم', 'vetra-portal-theme' ); ?></span></button></div><div class="vetra-admin-tabpanels">
		<?php ob_start(); ?><div class="vetra-admin-status-grid"><?php foreach ( $modules as $name => $active ) : ?><div class="vetra-admin-status"><span><?php echo esc_html( $name ); ?></span><strong class="vetra-status <?php echo $active ? 'is-active' : 'is-inactive'; ?>"><?php echo esc_html( $active ? __( 'فعال', 'vetra-portal-theme' ) : __( 'غیرفعال', 'vetra-portal-theme' ) ); ?></strong></div><?php endforeach; ?></div><?php $this->card( 'overview', 'dashboard-grid', __( 'وضعیت ماژول‌ها', 'vetra-portal-theme' ), ob_get_clean() ); ?>
		<?php ob_start(); ?><p><?php esc_html_e( 'برای تغییر ظاهر، فونت و پالت از Customizer استفاده کنید. توکن‌های VETRA روی صفحات عمومی و این پنل یکسان هستند.', 'vetra-portal-theme' ); ?></p><p><a class="button button-primary" href="<?php echo esc_url( customize_url() ); ?>"><?php esc_html_e( 'باز کردن Customizer', 'vetra-portal-theme' ); ?></a></p><?php $this->card( 'design', 'settings', __( 'Design System و ظاهر', 'vetra-portal-theme' ), ob_get_clean() ); ?>
		<?php ob_start(); ?><p><?php esc_html_e( 'مدیریت داده‌های پروژه و نقش‌های کاربران از مسیرهای استاندارد وردپرس انجام می‌شود.', 'vetra-portal-theme' ); ?></p><p><a class="button" href="<?php echo esc_url( admin_url( 'edit.php?post_type=vetra_project' ) ); ?>"><?php esc_html_e( 'مدیریت پروژه‌ها', 'vetra-portal-theme' ); ?></a></p><?php $this->card( 'projects', 'folder-project', __( 'پروژه‌ها و نقش‌ها', 'vetra-portal-theme' ), ob_get_clean() ); ?>
		<?php ob_start(); ?><?php $this->form( 'clear_css', __( 'بازسازی cache CSS', 'vetra-portal-theme' ) ); ?><p><a class="button" href="<?php echo esc_url( admin_url( 'plugins.php' ) ); ?>"><?php esc_html_e( 'مدیریت افزونه‌ها', 'vetra-portal-theme' ); ?></a></p><hr><h3><?php esc_html_e( 'پشتیبان تنظیمات', 'vetra-portal-theme' ); ?></h3><?php $this->form( 'export', __( 'دانلود JSON تنظیمات', 'vetra-portal-theme' ) ); ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" enctype="multipart/form-data"><?php wp_nonce_field( 'vetra_admin_import', 'vetra_admin_nonce' ); ?><input type="hidden" name="action" value="vetra_admin_action"><input type="hidden" name="vetra_operation" value="import"><input type="file" name="vetra_import" accept="application/json,.json" required><button class="button button-primary" type="submit"><?php esc_html_e( 'درون‌ریزی امن', 'vetra-portal-theme' ); ?></button></form><?php $this->card( 'system', 'settings', __( 'نگهداری و سیستم', 'vetra-portal-theme' ), ob_get_clean() ); ?></div></div></div></div><?php
	}
	private function form( $operation, $label ) { ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'vetra_admin_' . $operation, 'vetra_admin_nonce' ); ?><input type="hidden" name="action" value="vetra_admin_action"><input type="hidden" name="vetra_operation" value="<?php echo esc_attr( $operation ); ?>"><button class="button" type="submit"><?php echo esc_html( $label ); ?></button></form><?php }
	public function handle() {
		if ( ! current_user_can( 'manage_options' ) ) { wp_die( esc_html__( 'دسترسی کافی ندارید.', 'vetra-portal-theme' ) ); } $operation = sanitize_key( wp_unslash( $_POST['vetra_operation'] ?? '' ) ); if ( ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['vetra_admin_nonce'] ?? '' ) ), 'vetra_admin_' . $operation ) ) { wp_die( esc_html__( 'درخواست نامعتبر است.', 'vetra-portal-theme' ) ); }
		if ( 'clear_css' === $operation ) { vetra_clear_dynamic_css_cache(); wp_safe_redirect( add_query_arg( 'vetra_notice', 'css', admin_url( 'themes.php?page=vetra-dashboard' ) ) ); exit; } if ( 'export' === $operation ) { nocache_headers(); header( 'Content-Type: application/json; charset=utf-8' ); header( 'Content-Disposition: attachment; filename=vetra-settings.json' ); echo wp_json_encode( array( 'schema_version' => vetra_settings_schema_version(), 'settings' => vetra_operational_settings(), 'theme_mods' => get_theme_mods() ), JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT ); exit; }
		if ( 'import' === $operation ) { $file = $_FILES['vetra_import'] ?? array(); $checked = ! empty( $file['tmp_name'] ) ? wp_check_filetype_and_ext( $file['tmp_name'], sanitize_file_name( $file['name'] ?? '' ) ) : array(); if ( empty( $file['tmp_name'] ) || 'json' !== ( $checked['ext'] ?? '' ) || 'application/json' !== ( $checked['type'] ?? '' ) ) { wp_die( esc_html__( 'فایل JSON معتبر نیست.', 'vetra-portal-theme' ) ); } $data = json_decode( file_get_contents( $file['tmp_name'] ), true ); if ( ! is_array( $data ) || ! isset( $data['settings'] ) ) { wp_die( esc_html__( 'ساختار فایل تنظیمات معتبر نیست.', 'vetra-portal-theme' ) ); } update_option( 'vetra_operational_settings', vetra_settings_normalize( $data['settings'] ), false ); vetra_clear_dynamic_css_cache(); wp_safe_redirect( add_query_arg( 'vetra_notice', 'imported', admin_url( 'themes.php?page=vetra-dashboard' ) ) ); exit; }
	}
}
